version: '3.8'

services:
  flask_app:
    build:
      context: .
    container_name: exam_registration
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - meej-net

  reverse_proxy:
    image: caddy:latest
    container_name: caddy_proxy
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./caddy_config:/etc/caddy
      - caddy_data:/data
      - caddy_config_volume:/config
    depends_on:
      - flask_app
    networks:
      - meej-net

volumes:
  caddy_data:
  caddy_config_volume:

networks:
  meej-net: