services:
  flask_app:
    build: .
    container_name: exam_registration
    ports:
      - "5000:5000"
    volumes:
      - ./ExamRegistration.db:/app/ExamRegistration.db
    restart: always

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60

  reverse_proxy:
    image: caddy:latest
    container_name: caddy_proxy
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile

volumes:
  caddy_data:
  caddy_config:
