services:
  flask_app:
    build: .
    container_name: exam_registration
    ports:
      - "5000:5000"
    volumes:
      - ./ExamRegistration.db:/app/ExamRegistration.db
    restart: always

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60
volumes:
  caddy_data:
  caddy_config:
