services:
  flask_app:
    build: .
    container_name: exam_registration
    ports:
      - "5000:5000"
    volumes:
      - ./ExamRegistration.db:/app/ExamRegistration.db
    restart: always

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - flask_app
volumes:
  caddy_data:
  caddy_config:
