BEGIN TRANSACTION;

DROP TABLE IF EXISTS EXAMS;
DROP TABLE IF EXISTS EXAM_REGISTRATIONS;
DROP TABLE IF EXISTS LOCATION;
DROP TABLE IF EXISTS FACULTY;
DROP TABLE IF EXISTS STUDENTS;
DROP TABLE IF EXISTS PASSWORD_TOKENS;
DROP TABLE IF EXISTS AUTHENTICATION;

CREATE TABLE IF NOT EXISTS AUTHENTICATION (
    Auth_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CSN_Email TEXT NOT NULL UNIQUE,
    Password TEXT NOT NULL,
    Role TEXT NOT NULL CHECK (Role IN ('Student', 'Faculty')),
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS STUDENTS (
    StudentID INTEGER PRIMARY KEY,
    Auth_ID INTEGER NOT NULL,
    FirstName TEXT NOT NULL,
    LastName TEXT NOT NULL,
    Email TEXT NOT NULL UNIQUE,
    NSHEID TEXT NOT NULL UNIQUE,
    RegistrationDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (Auth_ID) REFERENCES AUTHENTICATION(Auth_ID)
);

-- Faculty table with personal information
CREATE TABLE IF NOT EXISTS FACULTY (
    FacultyID INTEGER PRIMARY KEY,
    Auth_ID INTEGER NOT NULL,
    FirstName TEXT NOT NULL,
    LastName TEXT NOT NULL,
    Email TEXT NOT NULL UNIQUE,
    Salary INTEGER,
    FOREIGN KEY (Auth_ID) REFERENCES AUTHENTICATION(Auth_ID)
);

-- Location table for exam locations
CREATE TABLE IF NOT EXISTS LOCATION (
    LocationID INTEGER PRIMARY KEY AUTOINCREMENT,
    CampusName TEXT NOT NULL,
    Building TEXT NOT NULL,
    RoomNumber TEXT NOT NULL,
    UNIQUE(CampusName, Building, RoomNumber)
);

-- Reservations table for exam scheduling
CREATE TABLE IF NOT EXISTS EXAMS (
    Exam_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    LocationID INTEGER NOT NULL,
    Exam_Name TEXT NOT NULL,
    ExamDate DATE NOT NULL,
    ExamTime TIME NOT NULL,
    ProctorID INTEGER NOT NULL,
    ExamCapacity INTEGER DEFAULT 20 CHECK (ExamCapacity <= 20),
    CurrentEnrollment INTEGER DEFAULT 0 CHECK (CurrentEnrollment <= ExamCapacity),
    Class TEXT NOT NULL,
    FOREIGN KEY (LocationID) REFERENCES LOCATION(LocationID),
    FOREIGN KEY (ProctorID) REFERENCES FACULTY(FacultyID)
);

-- Junction table for student exam registrations
CREATE TABLE IF NOT EXISTS EXAM_REGISTRATIONS (
    RegistrationID INTEGER PRIMARY KEY AUTOINCREMENT,
    StudentID INTEGER NOT NULL,
    Exam_ID INTEGER NOT NULL,
    RegistrationDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (StudentID) REFERENCES STUDENTS(StudentID),
    FOREIGN KEY (Exam_ID) REFERENCES EXAMS(Exam_ID),
    UNIQUE(StudentID, Exam_ID)
);

-- Password reset token management
CREATE TABLE IF NOT EXISTS PASSWORD_TOKENS (
    TokenID INTEGER PRIMARY KEY AUTOINCREMENT,
    Email TEXT NOT NULL,
    Token TEXT NOT NULL UNIQUE,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ExpiresAt TIMESTAMP NOT NULL DEFAULT (DATETIME(CURRENT_TIMESTAMP, '+1 hour')),
    Used INTEGER DEFAULT 0 CHECK (Used IN (0, 1)),
    FOREIGN KEY (Email) REFERENCES AUTHENTICATION(CSN_Email)
);

-- Trigger to update CurrentEnrollment when a student registers
CREATE TRIGGER IF NOT EXISTS after_registration_insert
AFTER INSERT ON EXAM_REGISTRATIONS
BEGIN
    UPDATE EXAMS 
    SET CurrentEnrollment = CurrentEnrollment + 1
    WHERE Exam_ID = NEW.Exam_ID;
END;

-- Trigger to update CurrentEnrollment when a student cancels registration
CREATE TRIGGER IF NOT EXISTS after_registration_delete
AFTER DELETE ON EXAM_REGISTRATIONS
BEGIN
    UPDATE EXAMS 
    SET CurrentEnrollment = CurrentEnrollment - 1
    WHERE Exam_ID = OLD.Exam_ID;
END;

-- Trigger to enforce 3 exam registration limit per student
CREATE TRIGGER IF NOT EXISTS check_exam_limit
BEFORE INSERT ON EXAM_REGISTRATIONS
BEGIN
    SELECT CASE 
        WHEN (
            SELECT COUNT(*) 
            FROM EXAM_REGISTRATIONS 
            WHERE StudentID = NEW.StudentID
        ) >= 3 
        THEN RAISE(ABORT, 'Students are limited to 3 exam registrations.')
    END;
END;

COMMIT;